repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 'v2.3.0'
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: ['feat', 'fix', 'ci', 'chore', 'test', 'docs', 'refactor']
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: 'v1.0.0-rc.1'
    hooks:
      - id: go-mod-tidy
      - id: go-vet-mod
      - id: go-fmt
      - id: go-staticcheck-mod
      - id: go-sec-mod
      - id: go-build-mod
      - id: go-test-mod
      - id: go-sec-mod
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
       - id: detect-private-key
