global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9090' ]
  - job_name: 'endpoints'
    static_configs:
      - targets: ['gateway:9312', 'manager:9410']

